### ISSUE TITLE
API doesn't work on .de-Servers

### ISSUE THREAD

**Issue by hagenschwass** [exchangegroup/api.marketplacer.com#1]
All of my API-requests (.de-Domain) result in code 500 Internal Server Error.

>curl -H "Authorization: Bearer 0d040685650a597b92b4529a3f94e3a6" https://www.bikeexchange.de/api/v2/client/adverts

**Comment by mipearson** [comment]
Hi,

Thanks for reporting this.

API Clients must send a `Content-Type: application/json` header as described in http://jsonapi.org/format/#content-negotiation

Normally you should have received a response letting you know this was the case - I've identified why it's not doing so and will be fixing this shortly.

**Comment by mipearson** [comment]
Correction: `Content-Type: application/vnd.api+json`.

API error response has now been fixed.

**Comment by hagenschwass** [comment]
Note: compliant to [RFC 2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.3) *Content-Type* isn't a valid request header. I can use *Content-Type* as an [entity header field](http://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html#sec7.1). For a request without content I need to use the "Accept" header. Was this beeing possible? I wouldn't mind, but .NET does.

**Comment by mipearson** [comment]
You're right - we should be checking for the header only if there is a request body attached.

**Comment by mipearson** [comment]
I've just pushed a change where it won't check the content type unless a request body is attached (eg, with a POST, PUT or PATCH request).

Can you give this a try now?

**Comment by hagenschwass** [comment]
Wait a second

**Comment by hagenschwass** [comment]
Great! Thank you very much! I have tested List Adverts and It was working.
