### ISSUE TITLE
Generate an API-Key

### ISSUE THREAD

**Issue by hagenschwass** [exchangegroup/api.marketplacer.com#2]
Up until recently, I could create some API-Keys by logging into the Retailer Account and click "API Anleitung" (API Instructions in German). In this section was the old instructions which allowed me to perform this function.

As of today, the new V2 API instrucitons ar elnked and I am unable to perform this function - create an API-Key.

Please can you confirm how I can complete this function / what has replaced this function.

**Comment by mipearson** [comment]
Hi,

Apologies - this functionality has now been restored.
