### ISSUE TITLE
Updating Advert.attributes.published

### ISSUE THREAD

**Issue by hagenschwass** [exchangegroup/api.marketplacer.com#3]
> curl -H "Authorization: Bearer REDACTED" -H "Content-Type: application:vnd.api+json" -X PUT -d "{\"data\":{\"attributes\":{\"published\":false}}}" https://www.bikeexchange.de/api/v2/client/adverts/100045865

I expected the Advert.attributes.published value to be set to false, but actually it stays true.

**Comment by mipearson** [comment]
Firstly please note that this is a public repo - please do not include API keys in issue reports.

There was an error where the POST data was not coming through correctly - this has now been fixed.

Note that you need to specify `application/vnd.api+json`, not `application:vnd.api+json`
