### ISSUE TITLE
Listing adverts responses 500 Internal Server Error

### ISSUE THREAD

**Issue by hagenschwass** [exchangegroup/api.marketplacer.com#4]
*curl -H "Authorization: Bearer REDACTED" "https://www.bikeexchange.de/api/v2/client/adverts?page%5Bnumber%5D=8&page%5Bsize%5D=100"

After replicating this issue you can hide the api key, anyway I will create a new one on fixed.

**Comment by mipearson** [comment]
Thanks for the report, this bug has been fixed.
