### ISSUE TITLE
Some issue creating an advert

### ISSUE THREAD

**Issue by hagenschwass** [exchangegroup/api.marketplacer.com#5]
```curl -H "Authorization: Bearer api_key" -H "Content-Type: application/vnd.api+json" -i -d "{\"data\":{\"type\":\"adverts\",\"attributes\":{\"title\":\"2014 Cannondale Trail 20 Single- Speed Boy´s\",\"description\":\"heelo description\",\"sale_type\":null,\"published\":false,\"code\":null,\"price\":299,\"condition\":\"new\",\"brand_slug\":\"cannondale\",\"taxon_slug\":\"jugend-kinderfahrrader\"}}}" -X POST https://www.bikeexchange.de/api/v2/client/adverts´´´

Result: Internal Server Error

**Comment by hagenschwass** [comment]
@ryande

**Comment by ryande** [comment]
@mipearson 
Pending your schedules, could someone pls take a look at this as Hagen is stuck and cant work any further in using the interface to create new adverts. 
Many Thanks, RMc

**Comment by radar** [comment]
Today is a public holiday in Australia and so we will attend to this on Monday.

**Comment by radar** [comment]
I have a patch pending for this currently. It might not be deployed by the end of the day because I am writing a Getting Started guide for the API instead and looking to get that finished by the end of the day.

A workaround that you can apply is to not send the `code` parameter through if it is `null`.

**Comment by radar** [comment]
This patch has been deployed to production. Could you please try again @hagenschwass and let me know how it goes?

**Comment by radar** [comment]
@hagenschwass I'm going to assume this issue is now fixed. Please let me know if it's not otherwise.
