### ISSUE TITLE
Issues with loading images to Jerks Bikes

### ISSUE THREAD

**Issue by BEUSA** [exchangegroup/api.marketplacer.com#9]
dev free lancer is stuck on images...

not sure if you can get anyone to help or check what is wrong

<?php
$service_url = 'https://www.bikeexchange.com/api/v2/client/adverts/100065329/images';
$curl = curl_init($service_url); 
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true); 
$data = array('data' => array('attributes' => array( 'image' => '@abc.png')));
$curl_post_data = json_encode($data);
curl_setopt($curl, CURLOPT_POSTFIELDS, $curl_post_data); 
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false); 
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Authorization: Bearer d9cea3f8810c19886d356d6ed87560ac', 'Content-Type: application/vnd.api+json'));
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, 'POST'); 

 $curl_response = curl_exec($curl); 
 echo '<pre>'; $json = json_decode($curl_response); 
 echo json_encode($json, JSON_PRETTY_PRINT); echo '</pre>'; 
 curl_close($curl);
 
 //curl -i -H 'Authorization: Bearer d9cea3f8810c19886d356d6ed87560ac, Content-Type: multipart/mixed' -F data[attributes][image]=@http://l.f29.img.vnecdn.net/2015/10/19/topstory-1445239390_490x294.jpg https://bikeexchange.com.au/api/v2/client/adverts/100065329/images

**Comment by mipearson** [comment]
Have responded to on #7
